using Avalonia;
using Avalonia.Input;
using Avalonia.Media.Imaging;
using Avalonia.Platform;
using PurplePen;
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace AvPurplePen
{
    // Holds onto the predefined cursor shapes so we don't keep creating new Cursor objects.
    // Also manages the mapping from MousePointerShape to Cursor.
    //
    // Most shapes come straight from the platform, but the sizing cursors are drawn by
    // PurplePen on platforms whose standard cursors are missing or mismatched -- see
    // UseCustomSizingFamily. The assets are generated by src/Tools/CursorGenerator.
    internal static class Cursors
    {
        public static Cursor Arrow = new Cursor(StandardCursorType.Arrow);
        public static Cursor Cross = new Cursor(StandardCursorType.Cross);
        public static Cursor Hand = new Cursor(StandardCursorType.Hand);
        public static Cursor Help = new Cursor(StandardCursorType.Help);
        public static Cursor IBeam = new Cursor(StandardCursorType.Ibeam);
        public static Cursor No = new Cursor(StandardCursorType.No);
        public static Cursor SizeAll = SizingCursor(UseCustomSizeAll(), "SizeAll", StandardCursorType.SizeAll);
        public static Cursor SizeNESW = SizingCursor(UseCustomSizingFamily(), "SizeNESW", StandardCursorType.BottomLeftCorner);
        public static Cursor SizeNS = SizingCursor(UseCustomSizingFamily(), "SizeNS", StandardCursorType.SizeNorthSouth);
        public static Cursor SizeNWSE = SizingCursor(UseCustomSizingFamily(), "SizeNWSE", StandardCursorType.BottomRightCorner);
        public static Cursor SizeWE = SizingCursor(UseCustomSizingFamily(), "SizeWE", StandardCursorType.SizeWestEast);
        public static Cursor UpArrow = new Cursor(StandardCursorType.UpArrow);
        public static Cursor Wait = new Cursor(StandardCursorType.Wait);
        public static Cursor MoveHandle = CreateCustomCursor("MoveHandleCursor32x32", new PixelPoint(0, 0));
        public static Cursor DeleteHandle = CreateCustomCursor("DeleteHandleCursor32x32", new PixelPoint(0, 0));
        public static Cursor HandDrag = CreateCustomCursor("HandDragCursor32x32", new PixelPoint(16, 14));

        public static Cursor CursorFromMousePointerShape(MousePointerShape shape)
        {
            switch (shape.PredefinedShape) {
            case PredefinedMousePointerShape.None:
            case PredefinedMousePointerShape.Arrow:
                return Arrow;
            case PredefinedMousePointerShape.Cross:
                return Cross;
            case PredefinedMousePointerShape.Hand:
                return Hand;
            case PredefinedMousePointerShape.Help:
                return Help;
            case PredefinedMousePointerShape.IBeam:
                return IBeam;
            case PredefinedMousePointerShape.No:
                return No;
            case PredefinedMousePointerShape.SizeAll:
                return SizeAll;
            case PredefinedMousePointerShape.SizeNESW:
                return SizeNESW;
            case PredefinedMousePointerShape.SizeNS:
                return SizeNS;
            case PredefinedMousePointerShape.SizeNWSE:
                return SizeNWSE;
            case PredefinedMousePointerShape.SizeWE:
                return SizeWE;
            case PredefinedMousePointerShape.UpArrow:
                return UpArrow;
            case PredefinedMousePointerShape.Wait:
                return Wait;
            case PredefinedMousePointerShape.MoveHandle:
                return MoveHandle;
            case PredefinedMousePointerShape.DeleteHandle:
                return DeleteHandle;
            case PredefinedMousePointerShape.HandDrag:
                return HandDrag;
            default:
                throw new ArgumentException($"Unknown predefined mouse pointer shape: {shape.PredefinedShape}");
            }
        }

        // Determine whether PurplePen substitutes its whole sizing cursor family for the
        // platform's standard cursors.
        //
        // Avalonia's macOS backend maps all four corner cursors and SizeAll to
        // [NSCursor crosshairCursor], so SizeNESW, SizeNWSE and SizeAll would all be
        // indistinguishable from Cross. macOS also has no four-headed-arrow cursor
        // reachable through public API, and the diagonal resize cursors it gained in
        // macOS 15 (+[NSCursor frameResizeCursorFromPosition:inDirections:]) are not used
        // by Avalonia. So on macOS PurplePen supplies all five shapes itself; replacing
        // only the three broken ones would leave SizeNS and SizeWE in a different style.
        static bool UseCustomSizingFamily()
        {
            return OperatingSystem.IsMacOS();
        }

        // Determine whether PurplePen substitutes only the four-headed arrow (SizeAll).
        //
        // X11 has good corner and axis resize cursors, so those are left alone on Linux,
        // but its SizeAll (XC_sizing) does not match the shapes drawn here, so the custom
        // four-headed arrow is used there as well. Windows has correct system cursors for
        // all five and uses them unchanged.
        static bool UseCustomSizeAll()
        {
            return UseCustomSizingFamily() || OperatingSystem.IsLinux();
        }

        // Get one sizing cursor, either PurplePen's own shape or the platform's standard one.
        // The custom cursors are 24x24 with the hotspot at the center. They are authored at
        // their point size because Avalonia discards a PNG's resolution metadata when handing
        // a custom cursor to the platform, so one pixel ends up as one point.
        //   useCustom     - true to load the PurplePen asset, false for the standard cursor
        //   cursorName    - base name of the asset, for example "SizeNESW"
        //   standardShape - standard cursor to use when useCustom is false
        static Cursor SizingCursor(bool useCustom, string cursorName, StandardCursorType standardShape)
        {
            if (useCustom)
                return CreateCustomCursor(cursorName + "Cursor24x24", new PixelPoint(12, 12));
            else
                return new Cursor(standardShape);
        }

        // Create a custom cursor from a PNG file and a hotspot.
        static Cursor CreateCustomCursor(string cursorName, PixelPoint hotspot)
        {
            Uri uri = new Uri($"avares://PurplePen/Assets/Cursors/{cursorName}.png");
            using Stream stream = AssetLoader.Open(uri);
            Bitmap cursorBitmap = new Bitmap(stream);
            return new Cursor(cursorBitmap, hotspot);
        }
    }
}
