//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurplePen.Livelox {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LiveloxResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LiveloxResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PurplePen.Livelox.LiveloxResources", typeof(LiveloxResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to administer this Livelox event. Please contact the event administrators..
        /// </summary>
        internal static string AccessDeniedToLiveloxEvent {
            get {
                return ResourceManager.GetString("AccessDeniedToLiveloxEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to another user.
        /// </summary>
        internal static string AnotherUser {
            get {
                return ResourceManager.GetString("AnotherUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging course setting information....
        /// </summary>
        internal static string AssemblingCourseSettingInformation {
            get {
                return ResourceManager.GetString("AssemblingCourseSettingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorizing....
        /// </summary>
        internal static string CreatingTokens {
            get {
                return ResourceManager.GetString("CreatingTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The course setting information has been uploaded. You will now be redirected to Livelox to finish the publishing process..
        /// </summary>
        internal static string ImportableEventCreatedInformation {
            get {
                return ResourceManager.GetString("ImportableEventCreatedInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Livelox event has been updated with new course setting information. Would you like to open the event&apos;s administration overview page in Livelox?.
        /// </summary>
        internal static string ImportableEventUpdatedInformation {
            get {
                return ResourceManager.GetString("ImportableEventUpdatedInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Livelox event....
        /// </summary>
        internal static string LoadingLiveloxEvent {
            get {
                return ResourceManager.GetString("LoadingLiveloxEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading user information....
        /// </summary>
        internal static string LoadingUserInfo {
            get {
                return ResourceManager.GetString("LoadingUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This window can now be closed. Please return to Purple Pen..
        /// </summary>
        internal static string PleaseReturnToPurplePen {
            get {
                return ResourceManager.GetString("PleaseReturnToPurplePen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing your approval....
        /// </summary>
        internal static string ProcessingLiveloxConsentResponse {
            get {
                return ResourceManager.GetString("ProcessingLiveloxConsentResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirecting to Livelox....
        /// </summary>
        internal static string RedirectingToLivelox {
            get {
                return ResourceManager.GetString("RedirectingToLivelox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing user....
        /// </summary>
        internal static string RemovingUser {
            get {
                return ResourceManager.GetString("RemovingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It looks like Livelox is taking a long time to respond. This can be caused by either poor connectivity or an error with the Livelox servers. Please try again in a while..
        /// </summary>
        internal static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request was not authorized. Livelox permissions for PurplePen may have been revoked. Please remove the user under the Settings section, and try again..
        /// </summary>
        internal static string UnauthorizedMessage {
            get {
                return ResourceManager.GetString("UnauthorizedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Livelox event....
        /// </summary>
        internal static string UpdatingLiveloxEvent {
            get {
                return ResourceManager.GetString("UpdatingLiveloxEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading course setting information....
        /// </summary>
        internal static string UploadingCourseSettingInformation {
            get {
                return ResourceManager.GetString("UploadingCourseSettingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for your approval in the browser window....
        /// </summary>
        internal static string WaitingForLiveloxConsentResponse {
            get {
                return ResourceManager.GetString("WaitingForLiveloxConsentResponse", resourceCulture);
            }
        }
    }
}
