//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurplePen {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommandNameText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandNameText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PurplePen.CommandNameText", typeof(CommandNameText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Bend.
        /// </summary>
        internal static string AddBend {
            get {
                return ResourceManager.GetString("AddBend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Control.
        /// </summary>
        internal static string AddControl {
            get {
                return ResourceManager.GetString("AddControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Corner.
        /// </summary>
        internal static string AddCorner {
            get {
                return ResourceManager.GetString("AddCorner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Mandatory Crossing Point.
        /// </summary>
        internal static string AddCrossingPoint {
            get {
                return ResourceManager.GetString("AddCrossingPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Finish.
        /// </summary>
        internal static string AddFinish {
            get {
                return ResourceManager.GetString("AddFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Gap.
        /// </summary>
        internal static string AddGap {
            get {
                return ResourceManager.GetString("AddGap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Map Exchange.
        /// </summary>
        internal static string AddMapExchange {
            get {
                return ResourceManager.GetString("AddMapExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Map Issue Point.
        /// </summary>
        internal static string AddMapIssue {
            get {
                return ResourceManager.GetString("AddMapIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Object.
        /// </summary>
        internal static string AddObject {
            get {
                return ResourceManager.GetString("AddObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Start.
        /// </summary>
        internal static string AddStart {
            get {
                return ResourceManager.GetString("AddStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Text Line.
        /// </summary>
        internal static string AddTextLine {
            get {
                return ResourceManager.GetString("AddTextLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Variation.
        /// </summary>
        internal static string AddVariation {
            get {
                return ResourceManager.GetString("AddVariation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Numbering.
        /// </summary>
        internal static string AutoNumbering {
            get {
                return ResourceManager.GetString("AutoNumbering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change All Controls Properties.
        /// </summary>
        internal static string ChangeAllControlsProperties {
            get {
                return ResourceManager.GetString("ChangeAllControlsProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Climb.
        /// </summary>
        internal static string ChangeClimb {
            get {
                return ResourceManager.GetString("ChangeClimb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Control Code.
        /// </summary>
        internal static string ChangeCode {
            get {
                return ResourceManager.GetString("ChangeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Codes.
        /// </summary>
        internal static string ChangeCodes {
            get {
                return ResourceManager.GetString("ChangeCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Control.
        /// </summary>
        internal static string ChangeControl {
            get {
                return ResourceManager.GetString("ChangeControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize Course Appearance.
        /// </summary>
        internal static string ChangeCourseAppearance {
            get {
                return ResourceManager.GetString("ChangeCourseAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Course Name.
        /// </summary>
        internal static string ChangeCourseName {
            get {
                return ResourceManager.GetString("ChangeCourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Course Order.
        /// </summary>
        internal static string ChangeCourseOrder {
            get {
                return ResourceManager.GetString("ChangeCourseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Course Properties.
        /// </summary>
        internal static string ChangeCourseProperties {
            get {
                return ResourceManager.GetString("ChangeCourseProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Control Description Standard.
        /// </summary>
        internal static string ChangeDescriptionStandard {
            get {
                return ResourceManager.GetString("ChangeDescriptionStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Displayed Courses.
        /// </summary>
        internal static string ChangeDisplayedCourses {
            get {
                return ResourceManager.GetString("ChangeDisplayedCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Line Appearance.
        /// </summary>
        internal static string ChangeLineAppearance {
            get {
                return ResourceManager.GetString("ChangeLineAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Map File.
        /// </summary>
        internal static string ChangeMapFile {
            get {
                return ResourceManager.GetString("ChangeMapFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Map Standard.
        /// </summary>
        internal static string ChangeMapStandard {
            get {
                return ResourceManager.GetString("ChangeMapStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Course Part Properties.
        /// </summary>
        internal static string ChangePartProperties {
            get {
                return ResourceManager.GetString("ChangePartProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Punch Card Layout.
        /// </summary>
        internal static string ChangePunchcardFormat {
            get {
                return ResourceManager.GetString("ChangePunchcardFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Punch Patterns.
        /// </summary>
        internal static string ChangePunchPatterns {
            get {
                return ResourceManager.GetString("ChangePunchPatterns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Map Scale.
        /// </summary>
        internal static string ChangeScale {
            get {
                return ResourceManager.GetString("ChangeScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Control Points.
        /// </summary>
        internal static string ChangeScore {
            get {
                return ResourceManager.GetString("ChangeScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Symbol.
        /// </summary>
        internal static string ChangeSymbol {
            get {
                return ResourceManager.GetString("ChangeSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Text.
        /// </summary>
        internal static string ChangeText {
            get {
                return ResourceManager.GetString("ChangeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Text Line.
        /// </summary>
        internal static string ChangeTextLine {
            get {
                return ResourceManager.GetString("ChangeTextLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Title.
        /// </summary>
        internal static string ChangeTitle {
            get {
                return ResourceManager.GetString("ChangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create {0} &amp;Files.
        /// </summary>
        internal static string CreateMapFiles {
            get {
                return ResourceManager.GetString("CreateMapFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Bend.
        /// </summary>
        internal static string DeleteBend {
            get {
                return ResourceManager.GetString("DeleteBend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Control.
        /// </summary>
        internal static string DeleteControl {
            get {
                return ResourceManager.GetString("DeleteControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Corner.
        /// </summary>
        internal static string DeleteCorner {
            get {
                return ResourceManager.GetString("DeleteCorner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Course.
        /// </summary>
        internal static string DeleteCourse {
            get {
                return ResourceManager.GetString("DeleteCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Fork/Loop.
        /// </summary>
        internal static string DeleteFork {
            get {
                return ResourceManager.GetString("DeleteFork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Map Exchange.
        /// </summary>
        internal static string DeleteMapExchangeAtControl {
            get {
                return ResourceManager.GetString("DeleteMapExchangeAtControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Object.
        /// </summary>
        internal static string DeleteObject {
            get {
                return ResourceManager.GetString("DeleteObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Text Line.
        /// </summary>
        internal static string DeleteTextLine {
            get {
                return ResourceManager.GetString("DeleteTextLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Course.
        /// </summary>
        internal static string DuplicateCourse {
            get {
                return ResourceManager.GetString("DuplicateCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Missing Fonts.
        /// </summary>
        internal static string IgnoreMissingFonts {
            get {
                return ResourceManager.GetString("IgnoreMissingFonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move All Controls.
        /// </summary>
        internal static string MoveAllControls {
            get {
                return ResourceManager.GetString("MoveAllControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Leg Bend.
        /// </summary>
        internal static string MoveBend {
            get {
                return ResourceManager.GetString("MoveBend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Control.
        /// </summary>
        internal static string MoveControl {
            get {
                return ResourceManager.GetString("MoveControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Control Number.
        /// </summary>
        internal static string MoveControlNumber {
            get {
                return ResourceManager.GetString("MoveControlNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Gap.
        /// </summary>
        internal static string MoveGap {
            get {
                return ResourceManager.GetString("MoveGap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Object.
        /// </summary>
        internal static string MoveObject {
            get {
                return ResourceManager.GetString("MoveObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Course.
        /// </summary>
        internal static string NewCourse {
            get {
                return ResourceManager.GetString("NewCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Event.
        /// </summary>
        internal static string NewEvent {
            get {
                return ResourceManager.GetString("NewEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relay Team Variations.
        /// </summary>
        internal static string RelayTeamVariations {
            get {
                return ResourceManager.GetString("RelayTeamVariations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Gap.
        /// </summary>
        internal static string RemoveGap {
            get {
                return ResourceManager.GetString("RemoveGap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Unused Controls.
        /// </summary>
        internal static string RemoveUnusedControls {
            get {
                return ResourceManager.GetString("RemoveUnusedControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate.
        /// </summary>
        internal static string Rotate {
            get {
                return ResourceManager.GetString("Rotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Competitor Load.
        /// </summary>
        internal static string SetCourseLoad {
            get {
                return ResourceManager.GetString("SetCourseLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize Description Text.
        /// </summary>
        internal static string SetCustomSymbolText {
            get {
                return ResourceManager.GetString("SetCustomSymbolText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Description Language.
        /// </summary>
        internal static string SetDescriptionLanguage {
            get {
                return ResourceManager.GetString("SetDescriptionLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Leg Flagging.
        /// </summary>
        internal static string SetLegFlagging {
            get {
                return ResourceManager.GetString("SetLegFlagging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish to Livelox.
        /// </summary>
        internal static string SetLiveloxImportableEventId {
            get {
                return ResourceManager.GetString("SetLiveloxImportableEventId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Print Area.
        /// </summary>
        internal static string SetPrintArea {
            get {
                return ResourceManager.GetString("SetPrintArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch.
        /// </summary>
        internal static string Stretch {
            get {
                return ResourceManager.GetString("Stretch", resourceCulture);
            }
        }
    }
}
