//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurplePen {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MiscText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MiscText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PurplePen.MiscText", typeof(MiscText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the text you wish to place on the map. After pressing OK, drag the mouse to place the text in the desired location..
        /// </summary>
        internal static string AddTextSpecialExplanation {
            get {
                return ResourceManager.GetString("AddTextSpecialExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Text.
        /// </summary>
        internal static string AddTextSpecialTitle {
            get {
                return ResourceManager.GetString("AddTextSpecialTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All controls.
        /// </summary>
        internal static string AllControls {
            get {
                return ResourceManager.GetString("AllControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to course setting for orienteering.
        /// </summary>
        internal static string AppSubtitle {
            get {
                return ResourceManager.GetString("AppSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple Pen.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The climb for a course must be a number 0-9999, or blank..
        /// </summary>
        internal static string BadClimb {
            get {
                return ResourceManager.GetString("BadClimb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The load for a course must be an integer 0-999999, or blank..
        /// </summary>
        internal static string BadLoad {
            get {
                return ResourceManager.GetString("BadLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The print scale must be a number between 100 and 100,000..
        /// </summary>
        internal static string BadScale {
            get {
                return ResourceManager.GetString("BadScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The points for a control must be an integer 1-999..
        /// </summary>
        internal static string BadScore {
            get {
                return ResourceManager.GetString("BadScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Operation.
        /// </summary>
        internal static string CancelOperation {
            get {
                return ResourceManager.GetString("CancelOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ca&amp;ncel Operation.
        /// </summary>
        internal static string CancelOperationWithShortcut {
            get {
                return ResourceManager.GetString("CancelOperationWithShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create folder &apos;{0}&apos; for the following reason:.
        /// </summary>
        internal static string CannotCreateDirectory {
            get {
                return ResourceManager.GetString("CannotCreateDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create &apos;{0}&apos; for the following reason:.
        /// </summary>
        internal static string CannotCreateFile {
            get {
                return ResourceManager.GetString("CannotCreateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create OCAD files for the following reason:.
        /// </summary>
        internal static string CannotCreateOcadFiles {
            get {
                return ResourceManager.GetString("CannotCreateOcadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load &apos;{0}&apos; for the following reason:.
        /// </summary>
        internal static string CannotLoadFile {
            get {
                return ResourceManager.GetString("CannotLoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load map file &apos;{0}&apos; for the following reason:.
        /// </summary>
        internal static string CannotLoadMapFile {
            get {
                return ResourceManager.GetString("CannotLoadMapFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot print &apos;{0}&apos; for the following reason:.
        /// </summary>
        internal static string CannotPrint {
            get {
                return ResourceManager.GetString("CannotPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read image file &apos;{0}&apos;..
        /// </summary>
        internal static string CannotReadImageFile {
            get {
                return ResourceManager.GetString("CannotReadImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read map for the following reason: &apos;{0}&apos; Using Optimize/Repair in OCAD may fix problems..
        /// </summary>
        internal static string CannotReadMap {
            get {
                return ResourceManager.GetString("CannotReadMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save &apos;{0}&apos; for the following reason:.
        /// </summary>
        internal static string CannotSaveFile {
            get {
                return ResourceManager.GetString("CannotSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current event has textual control descriptions in {0}. Would you like to change the language of control descriptions to {1}?.
        /// </summary>
        internal static string ChangeDescriptionLanguage {
            get {
                return ResourceManager.GetString("ChangeDescriptionLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the new text..
        /// </summary>
        internal static string ChangeTextSpecialExplanation {
            get {
                return ResourceManager.GetString("ChangeTextSpecialExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Text.
        /// </summary>
        internal static string ChangeTextTitle {
            get {
                return ResourceManager.GetString("ChangeTextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Clear Selection.
        /// </summary>
        internal static string ClearSelectionWithShortcut {
            get {
                return ResourceManager.GetString("ClearSelectionWithShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple Pen must be closed before loading the created OCAD files..
        /// </summary>
        internal static string ClosePPBeforeLoadingOCAD {
            get {
                return ResourceManager.GetString("ClosePPBeforeLoadingOCAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A control code must be one, two, or three letters or digits..
        /// </summary>
        internal static string CodeBadLength {
            get {
                return ResourceManager.GetString("CodeBadLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A control code should not begin with zero..
        /// </summary>
        internal static string CodeBeginsWithZero {
            get {
                return ResourceManager.GetString("CodeBeginsWithZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A control code must not contain a space..
        /// </summary>
        internal static string CodeContainsSpace {
            get {
                return ResourceManager.GetString("CodeContainsSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A control code should not look like another number when upside-down..
        /// </summary>
        internal static string CodeCouldBeUpsideDown {
            get {
                return ResourceManager.GetString("CodeCouldBeUpsideDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The control code &apos;{0}&apos; is already used by another control..
        /// </summary>
        internal static string CodeInUse {
            get {
                return ResourceManager.GetString("CodeInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A control code should be 31 or higher..
        /// </summary>
        internal static string CodeUnder31 {
            get {
                return ResourceManager.GetString("CodeUnder31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control {0}.
        /// </summary>
        internal static string Control_Code {
            get {
                return ResourceManager.GetString("Control_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Properties.
        /// </summary>
        internal static string CoursePropertiesTitle {
            get {
                return ResourceManager.GetString("CoursePropertiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Y.
        /// </summary>
        internal static string CtrlY {
            get {
                return ResourceManager.GetString("CtrlY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Z.
        /// </summary>
        internal static string CtrlZ {
            get {
                return ResourceManager.GetString("CtrlZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control {0} is currently used by the following courses: {1}. Do you want to delete this control anyway?.
        /// </summary>
        internal static string DeleteControlFromAllControls {
            get {
                return ResourceManager.GetString("DeleteControlFromAllControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control {0} is no longer used by any course. Do you want to delete this control from the control collection?.
        /// </summary>
        internal static string DeleteControlFromControlsCollection {
            get {
                return ResourceManager.GetString("DeleteControlFromControlsCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls {0} are no longer used by any course. Do you want to delete these controls from the control collection?.
        /// </summary>
        internal static string DeleteMultipleControlsFromControlsCollection {
            get {
                return ResourceManager.GetString("DeleteMultipleControlsFromControlsCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code &quot;{0}&quot; is used more than once..
        /// </summary>
        internal static string DuplicateCode {
            get {
                return ResourceManager.GetString("DuplicateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new climb in meters.
        /// </summary>
        internal static string EnterClimb {
            get {
                return ResourceManager.GetString("EnterClimb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new code.
        /// </summary>
        internal static string EnterCode {
            get {
                return ResourceManager.GetString("EnterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new course name.
        /// </summary>
        internal static string EnterCourseName {
            get {
                return ResourceManager.GetString("EnterCourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter feature size
        ///Use / for height on a slope
        ///Use | for two features.
        /// </summary>
        internal static string EnterDimensions {
            get {
                return ResourceManager.GetString("EnterDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new event title
        ///Use | to separate lines
        ///(affects all courses).
        /// </summary>
        internal static string EnterEventTitle {
            get {
                return ResourceManager.GetString("EnterEventTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new score.
        /// </summary>
        internal static string EnterScore {
            get {
                return ResourceManager.GetString("EnterScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new secondary title
        ///Use | to separate lines.
        /// </summary>
        internal static string EnterSecondaryTitle {
            get {
                return ResourceManager.GetString("EnterSecondaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new symbol meaning
        ///(affects all courses).
        /// </summary>
        internal static string EnterSymbolText {
            get {
                return ResourceManager.GetString("EnterSymbolText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new text.
        /// </summary>
        internal static string EnterTextLine {
            get {
                return ResourceManager.GetString("EnterTextLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esc.
        /// </summary>
        internal static string Esc {
            get {
                return ResourceManager.GetString("Esc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; already exists in the specified folder. Click the &quot;Back&quot; button and choose a new folder or a new event title..
        /// </summary>
        internal static string FileAlreadyExists {
            get {
                return ResourceManager.GetString("FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        internal static string Finish_Short {
            get {
                return ResourceManager.GetString("Finish_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Finish.
        /// </summary>
        internal static string FinishButtonText {
            get {
                return ResourceManager.GetString("FinishButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help file &apos;{0}&apos; could not be opened..
        /// </summary>
        internal static string HelpFileNotFound {
            get {
                return ResourceManager.GetString("HelpFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscape.
        /// </summary>
        internal static string Landscape {
            get {
                return ResourceManager.GetString("Landscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory crossing point.
        /// </summary>
        internal static string MandCrossing_Long {
            get {
                return ResourceManager.GetString("MandCrossing_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crossing.
        /// </summary>
        internal static string MandCrossing_Medium {
            get {
                return ResourceManager.GetString("MandCrossing_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        internal static string MandCrossing_Short {
            get {
                return ResourceManager.GetString("MandCrossing_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map exchange.
        /// </summary>
        internal static string MapExchange_Long {
            get {
                return ResourceManager.GetString("MapExchange_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange.
        /// </summary>
        internal static string MapExchange_Medium {
            get {
                return ResourceManager.GetString("MapExchange_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MX.
        /// </summary>
        internal static string MapExchange_Short {
            get {
                return ResourceManager.GetString("MapExchange_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another program has changed the map file &quot;{0}&quot;. Purple Pen will now reload the map..
        /// </summary>
        internal static string MapFileChanged {
            get {
                return ResourceManager.GetString("MapFileChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All: {0}.
        /// </summary>
        internal static string Margins_All {
            get {
                return ResourceManager.GetString("Margins_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left: {0}, Right: {1}, Top: {2}, Bottom: {3}.
        /// </summary>
        internal static string Margins_LRTB {
            get {
                return ResourceManager.GetString("Margins_LRTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The map file &quot;{0}&quot; could not be found.
        ///
        ///Most likely, the map file has been moved or deleted, or the Purple Pen file has been moved (possibly to a different computer). The map file must be present every time the Purple Pen event file is loaded. If you send a Purple Pen event file to another person, be sure that person has a copy of the map file also.
        ///
        ///After pressing OK, try to find a copy of the map file on your computer..
        /// </summary>
        internal static string MissingMapFile {
            get {
                return ResourceManager.GetString("MissingMapFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0} of Purple Pen is now available for download. (You are currently running version {1}.)
        ///
        ///To download the latest version, visit the Purple Pen web site by selecting &quot;Purple Pen Web Site&quot; in the Help menu..
        /// </summary>
        internal static string NewerVersionAvailable {
            get {
                return ResourceManager.GetString("NewerVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Next &gt;.
        /// </summary>
        internal static string NextButtonText {
            get {
                return ResourceManager.GetString("NextButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No courses were selected to print..
        /// </summary>
        internal static string NoCoursesSelected {
            get {
                return ResourceManager.GetString("NoCoursesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No symbol.
        /// </summary>
        internal static string NoSymbol {
            get {
                return ResourceManager.GetString("NoSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All controls are used in a course..
        /// </summary>
        internal static string NoUnusedControls {
            get {
                return ResourceManager.GetString("NoUnusedControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open &quot;{0}&quot;.
        /// </summary>
        internal static string OpenLastEvent {
            get {
                return ResourceManager.GetString("OpenLastEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page size is too small for any descriptions to be printed..
        /// </summary>
        internal static string PageTooSmall {
            get {
                return ResourceManager.GetString("PageTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to part {0}.
        /// </summary>
        internal static string PartN {
            get {
                return ResourceManager.GetString("PartN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plural.
        /// </summary>
        internal static string Plural {
            get {
                return ResourceManager.GetString("Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portrait.
        /// </summary>
        internal static string Portrait {
            get {
                return ResourceManager.GetString("Portrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Redo.
        /// </summary>
        internal static string RedoWithShortcut {
            get {
                return ResourceManager.GetString("RedoWithShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customized text requires a &quot;*&quot; to indicate where the object being modified is placed..
        /// </summary>
        internal static string RequireStar {
            get {
                return ResourceManager.GetString("RequireStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the changes you made to &apos;{0}&apos;?.
        /// </summary>
        internal static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to singular.
        /// </summary>
        internal static string Singular {
            get {
                return ResourceManager.GetString("Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        internal static string Start_Short {
            get {
                return ResourceManager.GetString("Start_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** If there exists a web site in the translated language that contains documentation for Purple Pen, enter the URL (including http) as the translation of this item. Otherwise leave it alone..
        /// </summary>
        internal static string TranslatedHelpWebSite {
            get {
                return ResourceManager.GetString("TranslatedHelpWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Undo.
        /// </summary>
        internal static string UndoWithShortcut {
            get {
                return ResourceManager.GetString("UndoWithShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha {0}.
        /// </summary>
        internal static string Version_Alpha {
            get {
                return ResourceManager.GetString("Version_Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta {0}.
        /// </summary>
        internal static string Version_Beta {
            get {
                return ResourceManager.GetString("Version_Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RC {0}.
        /// </summary>
        internal static string Version_RC {
            get {
                return ResourceManager.GetString("Version_RC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string VersionLabel {
            get {
                return ResourceManager.GetString("VersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
    }
}
