//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurplePen {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReportText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PurplePen.ReportText", typeof(ReportText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climb.
        /// </summary>
        internal static string ColumnHeader_Climb {
            get {
                return ResourceManager.GetString("ColumnHeader_Climb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string ColumnHeader_Code {
            get {
                return ResourceManager.GetString("ColumnHeader_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        internal static string ColumnHeader_Column {
            get {
                return ResourceManager.GetString("ColumnHeader_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        internal static string ColumnHeader_Control {
            get {
                return ResourceManager.GetString("ColumnHeader_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control codes.
        /// </summary>
        internal static string ColumnHeader_ControlCodes {
            get {
                return ResourceManager.GetString("ColumnHeader_ControlCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls.
        /// </summary>
        internal static string ColumnHeader_Controls {
            get {
                return ResourceManager.GetString("ColumnHeader_Controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        internal static string ColumnHeader_Course {
            get {
                return ResourceManager.GetString("ColumnHeader_Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        internal static string ColumnHeader_Distance {
            get {
                return ResourceManager.GetString("ColumnHeader_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string ColumnHeader_Item {
            get {
                return ResourceManager.GetString("ColumnHeader_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leg.
        /// </summary>
        internal static string ColumnHeader_Leg {
            get {
                return ResourceManager.GetString("ColumnHeader_Leg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string ColumnHeader_Length {
            get {
                return ResourceManager.GetString("ColumnHeader_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string ColumnHeader_Load {
            get {
                return ResourceManager.GetString("ColumnHeader_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string ColumnHeader_Location {
            get {
                return ResourceManager.GetString("ColumnHeader_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Courses.
        /// </summary>
        internal static string ColumnHeader_NumberOfCourses {
            get {
                return ResourceManager.GetString("ColumnHeader_NumberOfCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string ColumnHeader_Reason {
            get {
                return ResourceManager.GetString("ColumnHeader_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same symbol?.
        /// </summary>
        internal static string ColumnHeader_SameSymbol {
            get {
                return ResourceManager.GetString("ColumnHeader_SameSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visits.
        /// </summary>
        internal static string ColumnHeader_Visits {
            get {
                return ResourceManager.GetString("ColumnHeader_Visits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Summary for {0}.
        /// </summary>
        internal static string CourseSummary_Title {
            get {
                return ResourceManager.GetString("CourseSummary_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control cross-reference for {0}.
        /// </summary>
        internal static string CrossRef_Title {
            get {
                return ResourceManager.GetString("CrossRef_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Together Controls.
        /// </summary>
        internal static string EventAudit_CloseTogetherControls {
            get {
                return ResourceManager.GetString("EventAudit_CloseTogetherControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following table shows all control pairs that are within {0} meters of each other. The same symbol column shows whether the two controls have the same primary symbol (column D)..
        /// </summary>
        internal static string EventAudit_CloseTogetherExplanation {
            get {
                return ResourceManager.GetString("EventAudit_CloseTogetherExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Description Boxes.
        /// </summary>
        internal static string EventAudit_MissingBoxes {
            get {
                return ResourceManager.GetString("EventAudit_MissingBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular courses should indicate the amount of climb.
        /// </summary>
        internal static string EventAudit_MissingClimb {
            get {
                return ResourceManager.GetString("EventAudit_MissingClimb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All controls must have a main feature in column D.
        /// </summary>
        internal static string EventAudit_MissingD {
            get {
                return ResourceManager.GetString("EventAudit_MissingD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When &quot;between&quot; is in column G, two features must be shown in columns D and E.
        /// </summary>
        internal static string EventAudit_MissingEBetween {
            get {
                return ResourceManager.GetString("EventAudit_MissingEBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When &quot;junction&quot; or &quot;crossing&quot; is in column F, two features must be shown in columns D and E.
        /// </summary>
        internal static string EventAudit_MissingEJunction {
            get {
                return ResourceManager.GetString("EventAudit_MissingEJunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular courses should have a finish circle.
        /// </summary>
        internal static string EventAudit_MissingFinish {
            get {
                return ResourceManager.GetString("EventAudit_MissingFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Items in Courses.
        /// </summary>
        internal static string EventAudit_MissingItems {
            get {
                return ResourceManager.GetString("EventAudit_MissingItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course should have expected competitor load.
        /// </summary>
        internal static string EventAudit_MissingLoad {
            get {
                return ResourceManager.GetString("EventAudit_MissingLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No punch pattern defined.
        /// </summary>
        internal static string EventAudit_MissingPunch {
            get {
                return ResourceManager.GetString("EventAudit_MissingPunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Punch Patterns.
        /// </summary>
        internal static string EventAudit_MissingPunchPatterns {
            get {
                return ResourceManager.GetString("EventAudit_MissingPunchPatterns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score course should have score set for all controls or no controls.
        /// </summary>
        internal static string EventAudit_MissingScore {
            get {
                return ResourceManager.GetString("EventAudit_MissingScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Scores.
        /// </summary>
        internal static string EventAudit_MissingScores {
            get {
                return ResourceManager.GetString("EventAudit_MissingScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular courses should have a start triangle.
        /// </summary>
        internal static string EventAudit_MissingStart {
            get {
                return ResourceManager.GetString("EventAudit_MissingStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score courses should have a start triangle.
        /// </summary>
        internal static string EventAudit_MissingStartScore {
            get {
                return ResourceManager.GetString("EventAudit_MissingStartScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string EventAudit_No {
            get {
                return ResourceManager.GetString("EventAudit_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No problems found..
        /// </summary>
        internal static string EventAudit_NoProblems {
            get {
                return ResourceManager.GetString("EventAudit_NoProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Audit for {0}.
        /// </summary>
        internal static string EventAudit_Title {
            get {
                return ResourceManager.GetString("EventAudit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unused Controls.
        /// </summary>
        internal static string EventAudit_UnusedControls {
            get {
                return ResourceManager.GetString("EventAudit_UnusedControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following controls are present in the All Controls collection but are not used in any course. To remove them, use the &quot;Remove Unused Controls&quot; command on the &quot;Event&quot; menu. These controls will not be considered further in this report..
        /// </summary>
        internal static string EventAudit_UnusedControlsExplanation {
            get {
                return ResourceManager.GetString("EventAudit_UnusedControlsExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string EventAudit_Yes {
            get {
                return ResourceManager.GetString("EventAudit_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        internal static string LegLength_Average {
            get {
                return ResourceManager.GetString("LegLength_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1} controls, {2}, {3} m climb).
        /// </summary>
        internal static string LegLength_CourseInfo {
            get {
                return ResourceManager.GetString("LegLength_CourseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1} controls, {2}).
        /// </summary>
        internal static string LegLength_CourseInfoNoClimb {
            get {
                return ResourceManager.GetString("LegLength_CourseInfoNoClimb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leg Length Report for {0}.
        /// </summary>
        internal static string LegLength_Title {
            get {
                return ResourceManager.GetString("LegLength_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some controls are visited multiple times on the same course. The second load number counts each visit to a control separately..
        /// </summary>
        internal static string Load_ButterflyExists {
            get {
                return ResourceManager.GetString("Load_ButterflyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control load.
        /// </summary>
        internal static string Load_ControlLoadSection {
            get {
                return ResourceManager.GetString("Load_ControlLoadSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leg load.
        /// </summary>
        internal static string Load_LegLoadSection {
            get {
                return ResourceManager.GetString("Load_LegLoadSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some or all courses do not have competitor loads set for them. The loads listed below may be incorrect or missing for this reason. To set competitor loads, select &quot;Competitor Load&quot; from the &quot;Course&quot; menu..
        /// </summary>
        internal static string Load_MissingLoads {
            get {
                return ResourceManager.GetString("Load_MissingLoads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (only legs used by more than one course appear in the following table).
        /// </summary>
        internal static string Load_OnlyLegsMoreThanOnce {
            get {
                return ResourceManager.GetString("Load_OnlyLegsMoreThanOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competitor Load Summary for {0}.
        /// </summary>
        internal static string Load_Title {
            get {
                return ResourceManager.GetString("Load_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more courses has variations. Load numbers will be computed assuming that competitors are evenly distributed between forks..
        /// </summary>
        internal static string Load_VariationsExist {
            get {
                return ResourceManager.GetString("Load_VariationsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0} visits).
        /// </summary>
        internal static string Load_Visit {
            get {
                return ResourceManager.GetString("Load_Visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING:.
        /// </summary>
        internal static string Load_Warning {
            get {
                return ResourceManager.GetString("Load_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE: .
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: due to the number of legs specified, the fork at control {0} will not be used evenly. {1} leg(s) will use branch(es) {2}, while {3} leg(s) will use branch(es) {4}. .
        /// </summary>
        internal static string RelayVariation_BranchWarning {
            get {
                return ResourceManager.GetString("RelayVariation_BranchWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leg {0}.
        /// </summary>
        internal static string RelayVariation_LegHeader {
            get {
                return ResourceManager.GetString("RelayVariation_LegHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No relay teams have been defined yet. Selected the desired number of teams and legs and press the &quot;Assign Variations&quot; button..
        /// </summary>
        internal static string RelayVariation_NoTeams {
            get {
                return ResourceManager.GetString("RelayVariation_NoTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team {0}.
        /// </summary>
        internal static string RelayVariation_TeamNumber {
            get {
                return ResourceManager.GetString("RelayVariation_TeamNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relay Assignments for {0}.
        /// </summary>
        internal static string RelayVariation_Title {
            get {
                return ResourceManager.GetString("RelayVariation_Title", resourceCulture);
            }
        }
    }
}
