//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurplePen {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SelectionDescriptionText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SelectionDescriptionText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PurplePen.SelectionDescriptionText", typeof(SelectionDescriptionText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to away from control.
        /// </summary>
        internal static string AwayFromControl {
            get {
                return ResourceManager.GetString("AwayFromControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculated Length:.
        /// </summary>
        internal static string CalculatedLength {
            get {
                return ResourceManager.GetString("CalculatedLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climb:.
        /// </summary>
        internal static string Climb {
            get {
                return ResourceManager.GetString("Climb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competitor load:.
        /// </summary>
        internal static string CompetitorLoad {
            get {
                return ResourceManager.GetString("CompetitorLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to controls.
        /// </summary>
        internal static string Control_Plural {
            get {
                return ResourceManager.GetString("Control_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to control.
        /// </summary>
        internal static string Control_Singular {
            get {
                return ResourceManager.GetString("Control_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls in use:.
        /// </summary>
        internal static string ControlsInUse {
            get {
                return ResourceManager.GetString("ControlsInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls not in use:.
        /// </summary>
        internal static string ControlsNotInUse {
            get {
                return ResourceManager.GetString("ControlsNotInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All courses.
        /// </summary>
        internal static string CourseList_AllCourses {
            get {
                return ResourceManager.GetString("CourseList_AllCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string CourseList_None {
            get {
                return ResourceManager.GetString("CourseList_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course &quot;{0}&quot;.
        /// </summary>
        internal static string CourseName {
            get {
                return ResourceManager.GetString("CourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course &quot;{0}&quot;, Part {1}.
        /// </summary>
        internal static string CourseNameAndPart {
            get {
                return ResourceManager.GetString("CourseNameAndPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customized symbol description.
        /// </summary>
        internal static string CustomizedSymbolDesc {
            get {
                return ResourceManager.GetString("CustomizedSymbolDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entire leg.
        /// </summary>
        internal static string EntireLeg {
            get {
                return ResourceManager.GetString("EntireLeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finishes.
        /// </summary>
        internal static string Finish_Plural {
            get {
                return ResourceManager.GetString("Finish_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finish.
        /// </summary>
        internal static string Finish_Singular {
            get {
                return ResourceManager.GetString("Finish_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finish funnel.
        /// </summary>
        internal static string FinishFunnel {
            get {
                return ResourceManager.GetString("FinishFunnel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flagging:.
        /// </summary>
        internal static string Flagging {
            get {
                return ResourceManager.GetString("Flagging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to into control.
        /// </summary>
        internal static string IntoControl {
            get {
                return ResourceManager.GetString("IntoControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to into finish funnel.
        /// </summary>
        internal static string IntoFinishFunnel {
            get {
                return ResourceManager.GetString("IntoFinishFunnel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length:.
        /// </summary>
        internal static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line height:.
        /// </summary>
        internal static string LineHeight {
            get {
                return ResourceManager.GetString("LineHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load:.
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mandatory crossing points.
        /// </summary>
        internal static string MandCrossing_Plural {
            get {
                return ResourceManager.GetString("MandCrossing_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mandatory crossing point.
        /// </summary>
        internal static string MandCrossing_Singular {
            get {
                return ResourceManager.GetString("MandCrossing_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to map exchanges.
        /// </summary>
        internal static string MapExchange_Plural {
            get {
                return ResourceManager.GetString("MapExchange_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to map exchange.
        /// </summary>
        internal static string MapExchange_Singular {
            get {
                return ResourceManager.GetString("MapExchange_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map exchange at {0}.
        /// </summary>
        internal static string MapExchangeAtControl {
            get {
                return ResourceManager.GetString("MapExchangeAtControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncrossable Boundary.
        /// </summary>
        internal static string SpecialName_Boundary {
            get {
                return ResourceManager.GetString("SpecialName_Boundary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Name.
        /// </summary>
        internal static string SpecialName_CourseName {
            get {
                return ResourceManager.GetString("SpecialName_CourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dangerous Area.
        /// </summary>
        internal static string SpecialName_Dangerous {
            get {
                return ResourceManager.GetString("SpecialName_Dangerous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Descriptions.
        /// </summary>
        internal static string SpecialName_Descriptions {
            get {
                return ResourceManager.GetString("SpecialName_Descriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Aid Location.
        /// </summary>
        internal static string SpecialName_FirstAid {
            get {
                return ResourceManager.GetString("SpecialName_FirstAid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbidden Route.
        /// </summary>
        internal static string SpecialName_Forbidden {
            get {
                return ResourceManager.GetString("SpecialName_Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string SpecialName_Image {
            get {
                return ResourceManager.GetString("SpecialName_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string SpecialName_Line {
            get {
                return ResourceManager.GetString("SpecialName_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out-of-bounds Area.
        /// </summary>
        internal static string SpecialName_OOB {
            get {
                return ResourceManager.GetString("SpecialName_OOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional Crossing Point.
        /// </summary>
        internal static string SpecialName_OptCrossing {
            get {
                return ResourceManager.GetString("SpecialName_OptCrossing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle.
        /// </summary>
        internal static string SpecialName_Rectangle {
            get {
                return ResourceManager.GetString("SpecialName_Rectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Mark.
        /// </summary>
        internal static string SpecialName_RegMark {
            get {
                return ResourceManager.GetString("SpecialName_RegMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string SpecialName_Text {
            get {
                return ResourceManager.GetString("SpecialName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water Location.
        /// </summary>
        internal static string SpecialName_Water {
            get {
                return ResourceManager.GetString("SpecialName_Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White Out Area.
        /// </summary>
        internal static string SpecialName_WhiteOut {
            get {
                return ResourceManager.GetString("SpecialName_WhiteOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starts.
        /// </summary>
        internal static string Start_Plural {
            get {
                return ResourceManager.GetString("Start_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start.
        /// </summary>
        internal static string Start_Singular {
            get {
                return ResourceManager.GetString("Start_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text description:.
        /// </summary>
        internal static string TextDescription {
            get {
                return ResourceManager.GetString("TextDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text line.
        /// </summary>
        internal static string TextLine {
            get {
                return ResourceManager.GetString("TextLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appears above {0}, in all courses that contain {0}.
        /// </summary>
        internal static string TextLine_AboveAllCourses {
            get {
                return ResourceManager.GetString("TextLine_AboveAllCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appears above {0}, in this course only.
        /// </summary>
        internal static string TextLine_AboveThisCourse {
            get {
                return ResourceManager.GetString("TextLine_AboveThisCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appears below {0}, in all courses that contain {0}.
        /// </summary>
        internal static string TextLine_BelowAllCourses {
            get {
                return ResourceManager.GetString("TextLine_BelowAllCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appears below {0}, in this course only.
        /// </summary>
        internal static string TextLine_BelowThisCourse {
            get {
                return ResourceManager.GetString("TextLine_BelowThisCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total controls:.
        /// </summary>
        internal static string TotalControls {
            get {
                return ResourceManager.GetString("TotalControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total score:.
        /// </summary>
        internal static string TotalScore {
            get {
                return ResourceManager.GetString("TotalScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used in:.
        /// </summary>
        internal static string UsedIn {
            get {
                return ResourceManager.GetString("UsedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used in courses:.
        /// </summary>
        internal static string UsedInCourses {
            get {
                return ResourceManager.GetString("UsedInCourses", resourceCulture);
            }
        }
    }
}
