//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurplePen {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StatusBarText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StatusBarText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PurplePen.StatusBarText", typeof(StatusBarText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click left mouse button at the location of the bend.
        /// </summary>
        internal static string AddingBend {
            get {
                return ResourceManager.GetString("AddingBend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click left mouse button to place new control.
        /// </summary>
        internal static string AddingControl {
            get {
                return ResourceManager.GetString("AddingControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click left mouse button on the control circle to add a gap.
        /// </summary>
        internal static string AddingControlGap {
            get {
                return ResourceManager.GetString("AddingControlGap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click left mouse button to add a new corner.
        /// </summary>
        internal static string AddingCorner {
            get {
                return ResourceManager.GetString("AddingCorner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click left mouse button to place new mandatory crossing point.
        /// </summary>
        internal static string AddingCrossingPoint {
            get {
                return ResourceManager.GetString("AddingCrossingPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold down left mouse button and drag to create control descriptions.
        /// </summary>
        internal static string AddingDescription {
            get {
                return ResourceManager.GetString("AddingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click left mouse button to add existing control &quot;{0}&quot; to course.
        /// </summary>
        internal static string AddingExistingControl {
            get {
                return ResourceManager.GetString("AddingExistingControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click left mouse button to add existing mandatory crossing point to course.
        /// </summary>
        internal static string AddingExistingCrossingPoint {
            get {
                return ResourceManager.GetString("AddingExistingCrossingPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click left mouse button to add existing finish to course.
        /// </summary>
        internal static string AddingExistingFinish {
            get {
                return ResourceManager.GetString("AddingExistingFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click left mouse button to add existing map exchange to course.
        /// </summary>
        internal static string AddingExistingMapExchange {
            get {
                return ResourceManager.GetString("AddingExistingMapExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click left mouse button to add existing start to course.
        /// </summary>
        internal static string AddingExistingStart {
            get {
                return ResourceManager.GetString("AddingExistingStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click left mouse button to place new finish.
        /// </summary>
        internal static string AddingFinish {
            get {
                return ResourceManager.GetString("AddingFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold down left mouse button and drag to create a gap in the leg.
        /// </summary>
        internal static string AddingLegGap {
            get {
                return ResourceManager.GetString("AddingLegGap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold down left mouse button and drag to add a line segment; click the left mouse button to finish adding object.
        /// </summary>
        internal static string AddingLineArea {
            get {
                return ResourceManager.GetString("AddingLineArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click left mouse button to place new map exchange.
        /// </summary>
        internal static string AddingMapExchange {
            get {
                return ResourceManager.GetString("AddingMapExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click left mouse button to place new object.
        /// </summary>
        internal static string AddingObject {
            get {
                return ResourceManager.GetString("AddingObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click left mouse button to place new start.
        /// </summary>
        internal static string AddingStart {
            get {
                return ResourceManager.GetString("AddingStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold down left mouse button and drag to create text.
        /// </summary>
        internal static string AddingText {
            get {
                return ResourceManager.GetString("AddingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left mouse button: move/size rectangle;   Right mouse button: move map;   Scroll wheel: zoom in/out.
        /// </summary>
        internal static string DefaultRectangle {
            get {
                return ResourceManager.GetString("DefaultRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left mouse button: select object;   Right mouse button: move map;   Scroll wheel: zoom in/out.
        /// </summary>
        internal static string DefaultStatus {
            get {
                return ResourceManager.GetString("DefaultStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click left mouse button on a bend to remove it.
        /// </summary>
        internal static string DeletingBend {
            get {
                return ResourceManager.GetString("DeletingBend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click left mouse button on a corner to remove it.
        /// </summary>
        internal static string DeletingCorner {
            get {
                return ResourceManager.GetString("DeletingCorner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold down left mouse button and drag corner point to move it.
        /// </summary>
        internal static string DragCorner {
            get {
                return ResourceManager.GetString("DragCorner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move corner point to desired location and release mouse button.
        /// </summary>
        internal static string DraggingCorner {
            get {
                return ResourceManager.GetString("DraggingCorner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move object to desired location and release mouse button.
        /// </summary>
        internal static string DraggingObject {
            get {
                return ResourceManager.GetString("DraggingObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold down left mouse button and drag to move selected object.
        /// </summary>
        internal static string DragObject {
            get {
                return ResourceManager.GetString("DragObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click left mouse button on a gap in the control circle to remove it.
        /// </summary>
        internal static string RemovingControlGap {
            get {
                return ResourceManager.GetString("RemovingControlGap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click left mouse button on a gap in the leg to remove it.
        /// </summary>
        internal static string RemovingLegGap {
            get {
                return ResourceManager.GetString("RemovingLegGap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click left mouse button when the crossing point is rotated to the correct angle.
        /// </summary>
        internal static string RotatingObject {
            get {
                return ResourceManager.GetString("RotatingObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold down left mouse button and drag to size the selected object.
        /// </summary>
        internal static string SizeRectangle {
            get {
                return ResourceManager.GetString("SizeRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move edge(s) to desired location and release mouse button.
        /// </summary>
        internal static string SizingRectangle {
            get {
                return ResourceManager.GetString("SizingRectangle", resourceCulture);
            }
        }
    }
}
